[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
  "-C", 
  "link-arg=-fuse-ld=/usr/bin/mold"
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
  "-Zshare-generics=n",
  "-Zthreads=0",
] 